### ISSUE TITLE
Force CHAT's lazy overlap markers to be precise 

### ISSUE THREAD

**Issue by saulalbert** [saulalbert/unixclan#11]
CHAT has a 'lazy overlap' mode where the transcriber simply adds: `+< ` to the overlapping turn (the turn following the overlapped talk).

For example:

```
60    *PS006:	I had a .  
61    *PS002:	+< yeah .   
```
We want to force this to be precise - even if that's wrong, so that transcribers can correct the error by hand later. This means assuming that the entire overlapping turn overlaps with the entire overlapped turn e.g - the above example should come out like so:

```
60    *PS006:	⌈I had a⌉ .  
61    *PS002:	⌊ Yeah  ⌋ .   
```

**Comment by mumair01** [comment]
Can you elaborate on how this would apply on lines 170 and 171 of the example file? The previous line is already overlapped. This was exactly the problem I was having with the initial overlapping script as well. Lines 168 to 172 of the example file have [<] markers in successive lines, but no [>] marker indicating the start of the overlapped speech. This is a major problem that needs to be addressed in order to move forward.

**Comment by saulalbert** [comment]
I can see the problem here - the 'lazy' overlap introduces too many ambiguities when there are multiple overlaps on consecutive lines. I think it's probably not going to be possible to solve this one. 

I think a better approach would be to just not allow lazy overlaps at all - especially since we were going to force them to be non-lazy (and probably wrong) anyway.

I've removed all the lazy overlaps from the sample file - which should only have complete/accurate overlap markings in the latest version.

**Comment by mumair01** [comment]
So, after a lot of consideration, I think the lazy overlap markers become too ambiguous. We can completely ignore them and let the transcriber know what the symbol means in the documentation instead.
